source "https://rubygems.org"

gem "sinatra"
gem "haml"
gem "coffee-script"
gem "pg"
gem "dm-core"
gem "dm-migrations"
gem "dm-timestamps"
gem "dm-validations"
gem "dm-postgres-adapter"
gem "activerecord"
gem "sinatra-activerecord"